---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Install nginx
    yum: name=nginx state=latest

  - name: NGINX Plus | Starting NGINX Plus
    service:
      name: nginx
      state: started

  - name: NGINX | Change the config to support php-fpm 
    template: src=nginx.default.conf dest=/etc/nginx/conf.d/default.conf
    notify: restart nginx

  - name: Install PHP5
    yum: name=php state=latest

  - name: Install php-fpm
    yum: name=php-fpm state=latest

  - name: Start php-fpm 
    service:
      name: php-fpm
      state: started

  - name: Add php test application 
    template: src=test.app dest=/usr/share/nginx/html/test.app


